import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="max-w-screen-xl mx-auto">
        <header className="flex justify-between">
          <h1 className="pt-4 text-2xl font-bold">
            <Link href="">HJ&prime;s Blog</Link>
          </h1>
          <nav className="pt-4 space-x-4">
            <Link href="">home</Link>
            <Link href="/about">about</Link>
            <Link href="/posts">posts</Link>
            <Link href="/contact">contact</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
